@echo off&
echo.
echo ##### �����SSRSpeedĿ¼������ #####
echo.
if exist "%~dp0\main.py" (python main.py --version>ver.txt && for /f "delims=" %%i in (ver.txt) do ( set ver=%%i ) && echo ����SSRSpeedĿ¼�£���ӭʹ�� && echo ��ǰ�汾%%i && del ver.txt) else (echo �����SSRSpeedĿ¼�����У� )
if exist "%SystemRoot%\SysWOW64" path %path%;%windir%\SysNative;%SystemRoot%\SysWOW64;%~dp0
bcdedit >nul
if '%errorlevel%' NEQ '0' (echo ��ǰ�޹���ԱȨ��) else (echo ��ǰ�ѻ�ȡ����ԱȨ��)
if exist "%~dp0\clients\v2ray-core\v2ray.exe" ( set v1=1 ) else ( set v1=0 )
if exist "%~dp0\clients\v2ray-core\v2ctl.exe" ( set v2=1 ) else ( set v2=0 )
set /a v3=v1+v2
if %v3%==2 (echo �Ѱ�װV2ray-core ) else (echo δ��װV2ray-core )
:start
echo ====================================
echo 1����ʼ���٣��Զ������ã�
echo 2���״�����ǰ��װpip�����֧�֣���Ҫ����ԱȨ�ޣ�
echo 3����������
echo 4����ǰSSRSpeed�汾
echo 5��Ϊ�������л�ȡ����ԱȨ��
echo ====================================
echo ��ѡ��1~5����
choice /c 12345
if %errorlevel%==5 (goto :uac)
if %errorlevel%==4 (goto :ver)
if %errorlevel%==3 (goto :help)
if %errorlevel%==2 (goto :pip)
if %errorlevel%==1 (goto :test2)


:pip
if exist "%SystemRoot%\SysWOW64" path %path%;%windir%\SysNative;%SystemRoot%\SysWOW64;%~dp0
bcdedit >nul
if '%errorlevel%' NEQ '0' (echo #��ǰ�޹���ԱȨ�ޣ��޷���װ�� && echo. && echo #������ͨ������5��ȡȨ�ޣ����Ҽ��Թ���ԱȨ�������� && pause && goto :start) else (goto :pip2)
:pip2
python -m pip install --upgrade pip
pip3 install -r %~dp0%\requirements.txt
::pip3 install requests
::pip3 install pyyaml
::pip3 install Pillow
::pip3 install pysocks
::pip3 install aiohttp
::pip3 install aiohttp_socks
::pip3 install requests[socks]
::pip3 install flask
::pip3 install flask-cors
pause
goto :start

:ver
python main.py --version
pause
goto :start

:help
echo.
echo 1��ԭ�ģ�en��
echo 2�����루zh��
choice /c 12
if %errorlevel%==2 (goto :fy)
if %errorlevel%==1 (goto :yw)

:yw

echo.
echo Usage: main.py [options] arg1 arg2...
echo.
echo Options:
echo.
echo  --version                              show program's version number and exit
echo  -h, --help                             show this help message and exit
echo  -c GUICONFIG, --config=GUICONFIG       Load config generated by shadowsocksr-csharp.
echo  -u URL, --url=URL                      Load ssr config from subscription url.
echo  -m TEST_METHOD, --method=TEST_METHOD   Select test method in Select test method in [speedtestnet, fast, socket, stasync].
echo  -M TEST_MODE, --mode=TEST_MODE         Select test mode in [all,pingonly,wps].
echo  --include                              Filter nodes by group and remarks using keyword.
echo  --include-remark                       Filter nodes by remarks using keyword.
echo  --include-group                        Filter nodes by group name using keyword.
echo  --exclude                              Exclude nodes by group and remarks using keyword.
echo  --exclude-group                        Exclude nodes by group using keyword.
echo  --exclude-remark                       Exclude nodes by remarks using keyword.
echo  --use-ssr-cs                           Replace the ShadowsocksR-libev with the ShadowsocksR-C# (Only Windows)
echo  -g GROUP                               Manually set group.
echo  -y, --yes                              Skip node list confirmation before test.
echo  -C RESULT_COLOR, --color=RESULT_COLOR  Set the colors when exporting images..
echo  -S SORT_METHOD, --sort=SORT_METHOD     Select sort method in [speed,rspeed,ping,rping],default not sorted.
echo  -i IMPORT_FILE, --import=IMPORT_FILE   Import test result from json file and export it.
echo  --skip-requirements-check              Skip requirements check.
echo  --debug                                Run program in debug mode.
echo.
echo  Test Modes
echo  Mode                 Remark
echo  TCP_PING             Only tcp ping, no speed test
echo  WEB_PAGE_SIMULATION  Web page simulation test
echo  ALL                  Full speed test (exclude web page simulation)
echo.
echo  Test Methods
echo  Methods              Remark
echo  ST_ASYNC             Asynchronous download with single thread
echo  SOCKET               Raw socket with multithreading
echo  SPEED_TEST_NET       Speed Test Net speed test
echo  FAST                 Fast.com speed test
echo.
pause
goto :start

:fy

echo.
echo �÷���main.py [options] arg1 arg2...
echo.
echo ѡ�
echo.
echo  --version                               ��ʾ����İ汾�Ų��˳�
echo  -h��--help                              ��ʾ�˰�����Ϣ���˳�
echo  -c GUICONFIG��--config = GUICONFIG      ������shadowsocksr-csharp���ɵ����á�
echo  -u URL��--url = URL                     �Ӷ���URL����ssr���á�
echo  -m TEST_METHOD��--method = TEST_METHOD  ��[speedtestnet,fast,socket,stasync]��ѡ����Է�����
echo  -M TEST_MODE��--mode = TEST_MODE        ��[all,pingonly,wps]��ѡ�����ģʽ��
echo  --include                               ������˽ڵ㣬��ʹ�ùؼ���ע�͡�
echo  --include-remark                        ʹ�ùؼ���ͨ��ע�͹��˽ڵ㡣
echo  --include-group                         ʹ�ùؼ��ְ��������˽ڵ㡣
echo  --exclude                               �����ų��ڵ㣬��ʹ�ùؼ��ֽ���ע�͡�
echo  --exclude-group                         ʹ�ùؼ��ְ����ų��ڵ㡣
echo  --exclude-remark                        ͨ��ʹ�ùؼ��ֵ�ע���ų��ڵ㡣
echo  --use-ssr-cs                            ��ShadowsocksR-C���滻ShadowsocksR-libev����Windows��
echo  -g GROUP                                �ֶ������顣
echo  -y��--yes                               ����ǰ�����ڵ��б�ȷ�ϡ�
echo  -C RESULT_COLOR��--color = RESULT_COLOR ����ͼ��ʱ������ɫ��
echo  -S SORT_METHOD��--sort = SORT_METHOD    ��[speed,rspeed,ping,rping]��ѡ�����򷽷���Ĭ�ϲ�����
echo  -i IMPORT_FILE��--import = IMPORT_FILE  ��json�ļ�������Խ����������
echo  -skip-requirements-check                ����Ҫ���顣
echo  --debug                                 �ڵ���ģʽ�����г���
echo.
echo  ����ģʽ
echo  ģʽ                 ��ע
echo  TCP_PING             ��tcp ping�����ٶȲ���
echo  WEB_PAGE_SIMULATION  ��ҳģ�����
echo  ALL                  ȫ�ٲ��ԣ���������ҳģ�⣩
echo.
echo  ���Է���
echo  ����                 ��ע
echo  ST_ASYNC             ���߳��첽����
echo  SOCKET               ���ж��̵߳�ԭʼ�׽���
echo  SPEED_TEST_NET       SpeedTest.Net�ٶȲ���
echo  FAST                 Fast.com�ٶȲ���
echo.
pause
goto :start

:test2
echo.
echo      �����Զ���ѡ�����ջس���������
echo.
:test3
set /p a=���������Ķ�������(��������):
if "%a%"=="" (
goto :test3
) else (
goto :jx1
)
:jx1
echo      ����2�����ͨ���ո�ָ��ؼ���
set /p e=1.ʹ�ùؼ���ͨ��ע��ɸѡ�ڵ�:
set /p i=2.ͨ��ʹ�ùؼ��ֵ�ע���ų��ڵ�:
set /p k=3.�������������:
set /p m=4.����ͼ��ʱ������ɫ[origin,poor],Ĭ��origin:
set /p n=5.��[speed,rspeed,ping,rping]��ѡ���������򷽷���Ĭ�ϲ�������Ĭ��������:
echo.
if "%e%"=="" (
set e= && goto :jx1
) else (
set e=--include-remark %e% && goto :jx1
)
:jx1
if "%i%"=="" (
set i= && goto :jx2
) else (
set i=--exclude-remark %i% && goto :jx2
)
:jx2
if "%k%"=="" (
set k= && goto :jx3
) else (
set k=-g %k% && goto :jx3
)
:jx3
set l=-y && goto :jx4
:jx4
if "%m%"=="" (
set m= && goto :jx5
) else (
set m=-C %m% && goto :jx5
)
:jx5
if "%n%"=="" (
set n= && goto :jx6
) else (
set n=-s %n% && goto :jx6
)
:jx6
set o=--skip-requirements-check && goto :jx7
:jx7
echo python main.py -u "%a%" %e% %i% %k% %y% %m% %n%  %o%
echo.
python main.py -u "%a%" %e% %i% %k% %y% %m% %n%  %o%
pause
set a=
set e=
set i=
set k=
set y=
set m=
set n=
set o=
goto :start

:uac
echo.
if exist "%SystemRoot%\SysWOW64" path %path%;%windir%\SysNative;%SystemRoot%\SysWOW64;%~dp0
bcdedit >nul
if '%errorlevel%' NEQ '0' (goto UACPrompt) else (goto UACAdmin)
:UACPrompt
echo ��ʾ��ͨ��������װ��Ҫ����ԱȨ�ޣ�����4��
echo.
echo      ���Ի�ȡ����ԱȨ�ޣ���������
ping -n 3 127.0.0.1>nul && %1 start "" mshta vbscript:createobject("shell.application").shellexecute("""%~0""","::",,"runas",1)(window.close)&exit
exit /B
:UACAdmin
cd /d "%~dp0"
echo.
echo �ѻ�ȡ����ԱȨ��
echo.
pause
goto :start
@echo off&
echo.
echo ##### �����SSRSpeedĿ¼������ #####
echo.
if exist "%~dp0\main.py" (python main.py --version>ver.txt && for /f "delims=" %%i in (ver.txt) do ( set ver=%%i ) && echo ����SSRSpeedĿ¼�£���ӭʹ�� && echo ��ǰ�汾%%i && del ver.txt) else (echo �����SSRSpeedĿ¼�����У� )
if exist "%SystemRoot%\SysWOW64" path %path%;%windir%\SysNative;%SystemRoot%\SysWOW64;%~dp0
bcdedit >nul
if '%errorlevel%' NEQ '0' (echo ��ǰ�޹���ԱȨ��) else (echo ��ǰ�ѻ�ȡ����ԱȨ��)
if exist "%~dp0\clients\v2ray-core\v2ray.exe" ( set v1=1 ) else ( set v1=0 )
if exist "%~dp0\clients\v2ray-core\v2ctl.exe" ( set v2=1 ) else ( set v2=0 )
set /a v3=v1+v2
if %v3%==2 (echo �Ѱ�װV2ray-core ) else (echo δ��װV2ray-core )
:start
echo ====================================
echo 1����ʼ���٣��Զ������ã�
echo 2���״�����ǰ��װpip�����֧�֣���Ҫ����ԱȨ�ޣ�
echo 3����������
echo 4����ǰSSRSpeed�汾
echo 5��Ϊ�������л�ȡ����ԱȨ��
echo ====================================
echo ��ѡ��1~5����
choice /c 12345
if %errorlevel%==5 (goto :uac)
if %errorlevel%==4 (goto :ver)
if %errorlevel%==3 (goto :help)
if %errorlevel%==2 (goto :pip)
if %errorlevel%==1 (goto :test2)


:pip
if exist "%SystemRoot%\SysWOW64" path %path%;%windir%\SysNative;%SystemRoot%\SysWOW64;%~dp0
bcdedit >nul
if '%errorlevel%' NEQ '0' (echo #��ǰ�޹���ԱȨ�ޣ��޷���װ�� && echo. && echo #������ͨ������5��ȡȨ�ޣ����Ҽ��Թ���ԱȨ�������� && pause && goto :start) else (goto :pip2)
:pip2
python -m pip install --upgrade pip
pip3 install -r %~dp0%\requirements.txt
::pip3 install requests
::pip3 install pyyaml
::pip3 install Pillow
::pip3 install pysocks
::pip3 install aiohttp
::pip3 install aiohttp_socks
::pip3 install requests[socks]
::pip3 install flask
::pip3 install flask-cors
pause
goto :start

:ver
python main.py --version
pause
goto :start

:help
echo.
echo 1��ԭ�ģ�en��
echo 2�����루zh��
choice /c 12
if %errorlevel%==2 (goto :fy)
if %errorlevel%==1 (goto :yw)

:yw

echo.
echo Usage: main.py [options] arg1 arg2...
echo.
echo Options:
echo.
echo  --version                              show program's version number and exit
echo  -h, --help                             show this help message and exit
echo  -c GUICONFIG, --config=GUICONFIG       Load config generated by shadowsocksr-csharp.
echo  -u URL, --url=URL                      Load ssr config from subscription url.
echo  -m TEST_METHOD, --method=TEST_METHOD   Select test method in Select test method in [speedtestnet, fast, socket, stasync].
echo  -M TEST_MODE, --mode=TEST_MODE         Select test mode in [all,pingonly,wps].
echo  --include                              Filter nodes by group and remarks using keyword.
echo  --include-remark                       Filter nodes by remarks using keyword.
echo  --include-group                        Filter nodes by group name using keyword.
echo  --exclude                              Exclude nodes by group and remarks using keyword.
echo  --exclude-group                        Exclude nodes by group using keyword.
echo  --exclude-remark                       Exclude nodes by remarks using keyword.
echo  --use-ssr-cs                           Replace the ShadowsocksR-libev with the ShadowsocksR-C# (Only Windows)
echo  -g GROUP                               Manually set group.
echo  -y, --yes                              Skip node list confirmation before test.
echo  -C RESULT_COLOR, --color=RESULT_COLOR  Set the colors when exporting images..
echo  -S SORT_METHOD, --sort=SORT_METHOD     Select sort method in [speed,rspeed,ping,rping],default not sorted.
echo  -i IMPORT_FILE, --import=IMPORT_FILE   Import test result from json file and export it.
echo  --skip-requirements-check              Skip requirements check.
echo  --debug                                Run program in debug mode.
echo.
echo  Test Modes
echo  Mode                 Remark
echo  TCP_PING             Only tcp ping, no speed test
echo  WEB_PAGE_SIMULATION  Web page simulation test
echo  ALL                  Full speed test (exclude web page simulation)
echo.
echo  Test Methods
echo  Methods              Remark
echo  ST_ASYNC             Asynchronous download with single thread
echo  SOCKET               Raw socket with multithreading
echo  SPEED_TEST_NET       Speed Test Net speed test
echo  FAST                 Fast.com speed test
echo.
pause
goto :start

:fy

echo.
echo �÷���main.py [options] arg1 arg2...
echo.
echo ѡ�
echo.
echo  --version                               ��ʾ����İ汾�Ų��˳�
echo  -h��--help                              ��ʾ�˰�����Ϣ���˳�
echo  -c GUICONFIG��--config = GUICONFIG      ������shadowsocksr-csharp���ɵ����á�
echo  -u URL��--url = URL                     �Ӷ���URL����ssr���á�
echo  -m TEST_METHOD��--method = TEST_METHOD  ��[speedtestnet,fast,socket,stasync]��ѡ����Է�����
echo  -M TEST_MODE��--mode = TEST_MODE        ��[all,pingonly,wps]��ѡ�����ģʽ��
echo  --include                               ������˽ڵ㣬��ʹ�ùؼ���ע�͡�
echo  --include-remark                        ʹ�ùؼ���ͨ��ע�͹��˽ڵ㡣
echo  --include-group                         ʹ�ùؼ��ְ��������˽ڵ㡣
echo  --exclude                               �����ų��ڵ㣬��ʹ�ùؼ��ֽ���ע�͡�
echo  --exclude-group                         ʹ�ùؼ��ְ����ų��ڵ㡣
echo  --exclude-remark                        ͨ��ʹ�ùؼ��ֵ�ע���ų��ڵ㡣
echo  --use-ssr-cs                            ��ShadowsocksR-C���滻ShadowsocksR-libev����Windows��
echo  -g GROUP                                �ֶ������顣
echo  -y��--yes                               ����ǰ�����ڵ��б�ȷ�ϡ�
echo  -C RESULT_COLOR��--color = RESULT_COLOR ����ͼ��ʱ������ɫ��
echo  -S SORT_METHOD��--sort = SORT_METHOD    ��[speed,rspeed,ping,rping]��ѡ�����򷽷���Ĭ�ϲ�����
echo  -i IMPORT_FILE��--import = IMPORT_FILE  ��json�ļ�������Խ����������
echo  -skip-requirements-check                ����Ҫ���顣
echo  --debug                                 �ڵ���ģʽ�����г���
echo.
echo  ����ģʽ
echo  ģʽ                 ��ע
echo  TCP_PING             ��tcp ping�����ٶȲ���
echo  WEB_PAGE_SIMULATION  ��ҳģ�����
echo  ALL                  ȫ�ٲ��ԣ���������ҳģ�⣩
echo.
echo  ���Է���
echo  ����                 ��ע
echo  ST_ASYNC             ���߳��첽����
echo  SOCKET               ���ж��̵߳�ԭʼ�׽���
echo  SPEED_TEST_NET       SpeedTest.Net�ٶȲ���
echo  FAST                 Fast.com�ٶȲ���
echo.
pause
goto :start

:test2
echo.
echo      �����Զ���ѡ�����ջس���������
echo.
:test3
set /p a=���������Ķ�������(��������):
if "%a%"=="" (
goto :test3
) else (
goto :jx1
)
:jx1
echo      ����2�����ͨ���ո�ָ��ؼ���
set /p e=1.ʹ�ùؼ���ͨ��ע��ɸѡ�ڵ�:
set /p i=2.ͨ��ʹ�ùؼ��ֵ�ע���ų��ڵ�:
set /p k=3.�������������:
set /p m=4.����ͼ��ʱ������ɫ[origin,poor],Ĭ��origin:
set /p n=5.��[speed,rspeed,ping,rping]��ѡ���������򷽷���Ĭ�ϲ�������Ĭ��������:
echo.
if "%e%"=="" (
set e= && goto :jx1
) else (
set e=--include-remark %e% && goto :jx1
)
:jx1
if "%i%"=="" (
set i= && goto :jx2
) else (
set i=--exclude-remark %i% && goto :jx2
)
:jx2
if "%k%"=="" (
set k= && goto :jx3
) else (
set k=-g %k% && goto :jx3
)
:jx3
set l=-y && goto :jx4
:jx4
if "%m%"=="" (
set m= && goto :jx5
) else (
set m=-C %m% && goto :jx5
)
:jx5
if "%n%"=="" (
set n= && goto :jx6
) else (
set n=-s %n% && goto :jx6
)
:jx6
set o=--skip-requirements-check && goto :jx7
:jx7
echo python main.py -u "%a%" %e% %i% %k% %y% %m% %n%  %o%
echo.
python main.py -u "%a%" %e% %i% %k% %y% %m% %n%  %o%
pause
set a=
set e=
set i=
set k=
set y=
set m=
set n=
set o=
goto :start

:uac
echo.
if exist "%SystemRoot%\SysWOW64" path %path%;%windir%\SysNative;%SystemRoot%\SysWOW64;%~dp0
bcdedit >nul
if '%errorlevel%' NEQ '0' (goto UACPrompt) else (goto UACAdmin)
:UACPrompt
echo ��ʾ��ͨ��������װ��Ҫ����ԱȨ�ޣ�����4��
echo.
echo      ���Ի�ȡ����ԱȨ�ޣ���������
ping -n 3 127.0.0.1>nul && %1 start "" mshta vbscript:createobject("shell.application").shellexecute("""%~0""","::",,"runas",1)(window.close)&exit
exit /B
:UACAdmin
cd /d "%~dp0"
echo.
echo �ѻ�ȡ����ԱȨ��
echo.
pause
goto :start